\context ChordNames
	\chords {
		\set chordChanges = ##t
		% intro
		R2

		% aleluya al creador, aleluya al salvador
		g1 d1 e1:m b1:m
		% aleluya, aleluya, aleluya
		c1 d1 c2 d2 g1

		% interludio
		g2 
		\set chordChanges = ##f
		   g4 fis4:m
		\set chordChanges = ##t
		e1:m b1:m c1 a1:m7 d1 d1

		% aleluya al creador, aleluya al salvador
		g1 d1 e1:m b1:m
		% aleluya, aleluya, aleluya
		c1 d1 c2 d2 g1
	}
